import type { ReactNode } from "react";
import {
  IconAdd,
  IconArrowBack,
  IconArrowDownward,
  IconArrowForward,
  IconArrowUpward,
  IconAttachment,
  IconBarChart,
  IconBlock,
  IconBuild,
  IconCalendarToday,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconClose,
  IconCloudUpload,
  IconDashboard,
  IconDelete,
  IconDownload,
  IconEdit,
  IconEmail,
  IconError,
  IconExpandLess,
  IconExpandMore,
  IconFavorite,
  IconFilterList,
  IconFlag,
  IconFolder,
  IconHelp,
  IconHome,
  IconInfo,
  IconKeyboardArrowDown,
  IconKeyboardArrowLeft,
  IconKeyboardArrowRight,
  IconKeyboardArrowUp,
  IconLanguage,
  IconList,
  IconLocationOn,
  IconLock,
  IconMenu,
  IconPhone,
  IconPieChart,
  IconPrint,
  IconRefresh,
  IconSave,
  IconSearch,
  IconSend,
  IconSettings,
  IconShowChart,
  IconSort,
  IconStars,
  IconTableChart,
  IconThumbUp,
  IconUpload,
  IconVisibility,
  IconVisibilityOff,
  IconWarning,
  IconWork,
} from "../components/icons";

export const ICON_OPTIONS: Record<string, ReactNode> = {
  None: undefined,
  Add: <IconAdd />,
  ArrowBack: <IconArrowBack />,
  ArrowDownward: <IconArrowDownward />,
  ArrowForward: <IconArrowForward />,
  ArrowUpward: <IconArrowUpward />,
  Attachment: <IconAttachment />,
  BarChart: <IconBarChart />,
  Block: <IconBlock />,
  Build: <IconBuild />,
  CalendarToday: <IconCalendarToday />,
  Check: <IconCheck />,
  ChevronLeft: <IconChevronLeft />,
  ChevronRight: <IconChevronRight />,
  Close: <IconClose />,
  CloudUpload: <IconCloudUpload />,
  Dashboard: <IconDashboard />,
  Delete: <IconDelete />,
  Download: <IconDownload />,
  Edit: <IconEdit />,
  Email: <IconEmail />,
  Error: <IconError />,
  ExpandLess: <IconExpandLess />,
  ExpandMore: <IconExpandMore />,
  Favorite: <IconFavorite />,
  FilterList: <IconFilterList />,
  Flag: <IconFlag />,
  Folder: <IconFolder />,
  Help: <IconHelp />,
  Home: <IconHome />,
  Info: <IconInfo />,
  KeyboardArrowDown: <IconKeyboardArrowDown />,
  KeyboardArrowLeft: <IconKeyboardArrowLeft />,
  KeyboardArrowRight: <IconKeyboardArrowRight />,
  KeyboardArrowUp: <IconKeyboardArrowUp />,
  Language: <IconLanguage />,
  List: <IconList />,
  LocationOn: <IconLocationOn />,
  Lock: <IconLock />,
  Menu: <IconMenu />,
  Phone: <IconPhone />,
  PieChart: <IconPieChart />,
  Print: <IconPrint />,
  Refresh: <IconRefresh />,
  Save: <IconSave />,
  Search: <IconSearch />,
  Send: <IconSend />,
  Settings: <IconSettings />,
  ShowChart: <IconShowChart />,
  Sort: <IconSort />,
  Stars: <IconStars />,
  TableChart: <IconTableChart />,
  ThumbUp: <IconThumbUp />,
  Upload: <IconUpload />,
  Visibility: <IconVisibility />,
  VisibilityOff: <IconVisibilityOff />,
  Warning: <IconWarning />,
  Work: <IconWork />,
};

export const iconArgType = {
  control: "select" as const,
  options: Object.keys(ICON_OPTIONS),
  mapping: ICON_OPTIONS,
};
